# Generated by Django 2.0.6 on 2018-07-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=4)),
                ('uname', models.CharField(max_length=50)),
                ('pwd', models.CharField(blank=True, max_length=50, null=True)),
                ('kodeurusan', models.IntegerField()),
                ('kodesuburusan', models.IntegerField()),
                ('kodeorganisasi', models.CharField(max_length=4)),
                ('hakakses', models.CharField(max_length=16)),
                ('is_bendahara_pembantu', models.CharField(max_length=1)),
                ('kegiatan', models.CharField(blank=True, max_length=1000, null=True)),
                ('nama_bendahara_pembantu', models.CharField(blank=True, max_length=255, null=True)),
                ('organisasi', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'pengguna',
                'managed': False,
            },
        ),
    ]
