# Generated by Django 2.2 on 2021-02-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sipkd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pengguna',
        ),
    ]
